/*Relational Schema for WAKAMONO's dataset*/

Employee(EmpID, EmpSalary, EmpRole, EmpPhone, EmpStreet, EmpCity, EmpState, EmpZip, EmpFName, EmpLName)
EmployeeShift(ShiftNum, ShiftDate, ClockIN, ClockOut, ScheduledLength, EmpID) 
	Foreign key (EmpID) references Employee (EmpID) 
Order(OrderNum, Date, OrderType, finalPrice, EmpID, CustomerID)
	Foreign key (EmpID) references Employee (EmpID)
	Foreign key (CustomerID) references Customer (CustomerID)
OrderLine(OrderLineNum, Quantity, Price, Discount, OrderNum, ProductNum) 
	Foreign key (OrderNum) references Order (OrderNum)
Foreign key (ProductNum) references Product (ProductNum)
MenuItems(MenuItemID, ProductIngredient, ProductCategory, ProductNum) 
	Foreign key (ProductNum) references Product (ProductNum)
Vendor(VendorID, VendorCity, VendorState, VendorZip, VendorStreet, VendorName, VendorPhone)
Product(ProductNum, ProductName, ProductPrice, vendorID)
	Foreign key (vendorID) references Vendor (VendorID) 
Customer(CustomerID, CustCity, CustState, CustStreet, CustZip, CustEmail, CustFName, CustLName, CustPhone)
Reservation(ReservationNum, GroupSize, ResDay, ResTime, CustomerID)
	Foreign key (CustomerID) references Customer (CustomerID) 
